M48
; DRILL file {KiCad 7.0.6} date Fri Sep 27 11:16:27 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-27T11:16:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.3228Y-5.2756
X7.3228Y-6.378
X9.0354Y-5.2756
X9.0354Y-6.378
T0
M30
